language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

before_script:
    - mkdir -p web/code-coverage
    - composer install --dev --prefer-source

script:
    - bin/atoum

notifications:
    email:
        recipients:
            - ci@verylastroom.com
        on_success: change
        on_failure: change
